stages:
  - build
  - deploy

build-job:
  stage: build
  environment: production
  artifacts:
    paths:
      - "dist/"
      - "node_modules/"
    when: always
  before_script:
    - npm ci
  script:
    - npm run build
    - npm run seed:prod:run

deploy-pm2-job:
  stage: deploy
  environment: production
  dependencies:
    - build-job
  script: 
    - mkdir -p /var/www/recipe/server
    - rm -rf /var/www/recipe/server/*
    - mv dist/* /var/www/recipe/server
    - mv node_modules/ /var/www/recipe/server
    - pm2 stop main
    - pm2 del main
    - pm2 start /var/www/recipe/server/main.js
