stages:
  - build
  - deploy

build-job:
  stage: build
  environment: production
  artifacts:
    paths:
      - "dist"
      - "node_modules"
      - "ecosystem.config.js"
    when: always
  script:
    - npm ci
    - npm run build

deploy-pm2-job:
  stage: deploy
  environment: production
  dependencies:
    - build-job
  script: 
    - mkdir -p /var/www/recipe/server
    - rm -rf /var/www/recipe/server/*
    - mv dist/* /var/www/recipe/server
    - mv node_modules /var/www/recipe/server
    - mv ecosystem.config.js /var/www/recipe/server
    - cd /var/www/recipe/server
    - node dist/db/seeds
    - pm2 startOrRestart ecosystem.config.js
