stages:
  - build
  - deploy

build-job:
  stage: build
  environment: production
  artifacts:
    paths:
      - "build/"
    when: always
  before_script:
    - npm ci
  script:
    - npm run build
    - npm run seed:prod:run

deploy-pm2-job:
  stage: deploy
  environment: production
  dependencies:
    - build-job
  script: 
    - mkdir -p /var/www/recipe/server
    - mv build/* /var/www/recipe/server
    - pm2 start /var/www/recipe/server/main.js --attach
