stages:
  - deploy

deploy:
  tags:
    - production
  stage: deploy
  script: npm i && npm run build && npm run seed:prod:run && screen -S site_run_prod_back -d -m npm run start:prod
  environment: production
