stages:
  - build
  - deploy

build-job:
  stage: build
  environment: production
  artifacts:
    paths:
      - "dist"
      - "node_modules"
      - "ecosystem.config.js"
    when: always
  script:
    - npm ci
    - npm run build

deploy-pm2-job:
  stage: deploy
  environment: production
  dependencies:
    - build-job
  script: 
    - mkdir -p /var/www/recipe/backend
    - rm -rf /var/www/recipe/backend/*
    - cp -r dist node_modules ecosystem.config.js /var/www/recipe/backend
    - cd /var/www/recipe/backend
    - node dist/db/seeds
    - pm2 startOrRestart ecosystem.config.js
