install-deps:
  tags:
    - production
  stage: build
  script: npm ci
  environment: production

build:
  tags:
    - production
  stage: build
  script: npm run build
  environment: production

deploy:
  tags:
    - production
  stage: deploy
  script: screen -S site_run_prod_back -d -m npm run start:prod
  environment: production
