install-deps:
  tags:
    - production
  stage: build
  script: npm i
  environment: production

build:
  tags:
    - production
  stage: build
  script: npm run build
  environment: production

seeds:
  tags:
    - production
  stage: build
  script: cp src/db/seeds/*.json dist/db/seeds && npm run seed:prod:run
  environment: production

deploy:
  tags:
    - production
  stage: deploy
  script: screen -S site_run_prod_back -d -m npm run start:prod
  environment: production
